/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPetNewRouteImport } from './routes/_protected/pet/new'
import { Route as ProtectedPetProfileIdRouteImport } from './routes/_protected/pet/profile.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPetNewRoute = ProtectedPetNewRouteImport.update({
  id: '/pet/new',
  path: '/pet/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPetProfileIdRoute = ProtectedPetProfileIdRouteImport.update({
  id: '/pet/profile/$id',
  path: '/pet/profile/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/pet/new': typeof ProtectedPetNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pet/profile/$id': typeof ProtectedPetProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/pet/new': typeof ProtectedPetNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pet/profile/$id': typeof ProtectedPetProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/pet/new': typeof ProtectedPetNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/pet/profile/$id': typeof ProtectedPetProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/pet/new' | '/api/auth/$' | '/pet/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/pet/new' | '/api/auth/$' | '/pet/profile/$id'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/pet/new'
    | '/api/auth/$'
    | '/_protected/pet/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pet/new': {
      id: '/_protected/pet/new'
      path: '/pet/new'
      fullPath: '/pet/new'
      preLoaderRoute: typeof ProtectedPetNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pet/profile/$id': {
      id: '/_protected/pet/profile/$id'
      path: '/pet/profile/$id'
      fullPath: '/pet/profile/$id'
      preLoaderRoute: typeof ProtectedPetProfileIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedPetNewRoute: typeof ProtectedPetNewRoute
  ProtectedPetProfileIdRoute: typeof ProtectedPetProfileIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPetNewRoute: ProtectedPetNewRoute,
  ProtectedPetProfileIdRoute: ProtectedPetProfileIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
